### ISSUE TITLE
MC output seems strange

### ISSUE THREAD

**Issue by ejunprung** [PathmindAI/pathmind-api#36]
If you run MC, the final reward is the same for each episode.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/5703667/139959855-c7971274-5eee-4bb1-b45d-15cb6b856f7e.png">

But if I run the simulation manually one by one, the final rewards are different each time. I'm not sure why, is it related to seeds?

**Comment by ejunprung** [comment]
Results from running manually one-by-one so far.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/5703667/139960767-0e2df0fa-ee0d-402f-87d2-197a691b2462.png">

**Comment by slinlee** [comment]
is this with all models?

**Comment by ejunprung** [comment]
Yeah. We think it's using the same seed for each episode. I think we need to reset the seed after each MC iteration.

**Comment by SaharEs** [comment]
@ejunprung I found what was the issue. When looping through episodes, `done` wasn't reseting to False, also `self.reset()` needs to be called too. 
<img width="588" alt="Screen Shot 2021-11-04 at 11 15 13 AM" src="https://user-images.githubusercontent.com/48958471/140345453-94f67a32-1b22-48ef-b4f1-6d527ff1d12d.png">

Now it is working fine but taking quite long time to run. I think it is slow because it is writing to the csv file at the end of each episode. Maybe if we write the results once at the end of MC it would be faster.
